### ISSUE TITLE
subscribe: Make SubscribeOptions reactive

### ISSUE THREAD

**Issue by pleek91** [PrefectHQ/vue-compositions#22]
Currently if you do something like this you get a typescript error. While technically it'll work it won't be reactive. Meaning if you change the interval using reactivity the subscription will not update. 

```typescript
const options = computed<SubscriptionOptions>(() => ({
  interval: props.loading ? 5000 : undefined
}))
const subscription = subscribe(Logs.filter.bind(Logs), [filter.value], options)
```

**Comment by znicholasbrown** [comment]
Closed by #226
