### ISSUE TITLE
Bug: Review useRouteQueryParam format.set()

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/vue-compositions#333]
As discussed in https://github.com/PrefectHQ/vue-compositions/pull/332, format.set(query, value) in useRouteQueryParam is triggering updates in more than the query which is causing reactive affects to trigger multiple times.  We fixed this with a bandaid in https://github.com/PrefectHQ/vue-compositions/pull/332 so the impact is smaller but in slower time we shoudl dig and see if we can find a route cause and fix.

**Comment by pleek91** [comment]
This should be fixed by https://github.com/vuejs/core/pull/5912

**Comment by pleek91** [comment]
Closed by #345
